services:
  backend:
    image: jaehyuun/careride
    container_name: careride
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - redis
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - REDIS_HOST=redis

  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    restart: always